### ISSUE TITLE
[REQ]

### ISSUE THREAD

**Issue by kavin31287** [sysdotini/hibiki#155]
**Describe the feature you'd like**
I am watching for all in one bot for free. Because we donot have time to add all bots . Also we forget prefix.pls add ticket system , coin system , staff applications, giveaway also.
Pls

**Comment by nocturnodev** [comment]
No

**Comment by lambdagg** [comment]
No

**Comment by nocturnodev** [comment]
No

**Comment by sysdotini** [comment]
1) You can change the prefix with `h!prefix`
2) Giveaways and tickets are planned
